version: '3'

services:
  web:
    build: .
    volumes:
       - .:/code
    expose:
       - 8000
    command: python /code/mysite/manage.py runserver 0.0.0.0:8000

  caddy:
    image: caddy:latest
    restart: unless-stopped
    depends_on:
      - web
    links:
      - web:web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/mysite/keycapvision/static:/srv/static/
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config:
